"""
ISO 8650-1 (ACSE) Fields
"""
from scapy.asn1fields import *
from .tags import ASN1_Tags_ACSE


class ASN1F_AARQ_TYPE(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Tags_ACSE.AARQ_TYPE_TAG


class ASN1F_AARE_TYPE(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Tags_ACSE.AARE_TYPE_TAG


class ASN1F_APPLICATION_CONTEXT_NAME(ASN1F_OID):
    ASN1_tag = ASN1_Tags_ACSE.APPLICATION_CONTEXT_NAME_TAG


class ASN1F_CALLED_AP_TITLE_FORM_2(ASN1F_OID):
    ASN1_tag = ASN1_Tags_ACSE.CALLED_AP_TITLE_FORM_2_TAG


class ASN1F_CALLED_AE_QUALIFIER_FORM_2(ASN1F_INTEGER):
    ASN1_tag = ASN1_Tags_ACSE.CALLED_AE_QUALIFIER_FORM_2_TAG


class ASN1F_AARE_RESULT_TYPE(ASN1F_enum_INTEGER):
    ASN1_tag = ASN1_Tags_ACSE.AARE_RESULT_TYPE_TAG


class ASN1F_ACSE_SERVICE_USER(ASN1F_enum_INTEGER):
    ASN1_tag = ASN1_Tags_ACSE.ACSE_SERVICE_USER_TAG


class ASN1F_CALLING_AP_TITLE_FORM_2(ASN1F_OID):
    ASN1_tag = ASN1_Tags_ACSE.CALLING_AP_TITLE_FORM_2_TAG


class ASN1F_CALLING_AE_QUALIFIER_FORM_2(ASN1F_INTEGER):
    ASN1_tag = ASN1_Tags_ACSE.CALLING_AE_QUALIFIER_FORM_2_TAG


class ASN1F_USER_INFORMATION(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Tags_ACSE.USER_INFORMATION_TAG


class ASN1F_EXTERNAL_T(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Tags_ACSE.EXTERNAL_T_TAG


class ASN1F_INDIRECT_REFERENCE(ASN1F_INTEGER):
    ASN1_tag = ASN1_Tags_ACSE.INDIRECT_REFERENCE_TAG


class ASN1F_ACSE_MMS_DATA(ASN1F_SEQUENCE):
    ASN1_tag = ASN1_Tags_ACSE.MMS_DATA_TAG
