"""
MMS ASN1 Type Mappings
"""
from scapy.asn1.asn1 import ASN1_SEQUENCE, ASN1_INTEGER, ASN1_ISO646_STRING, ASN1_BOOLEAN, ASN1_BIT_STRING, ASN1_NULL, \
    ASN1_STRING, ASN1_UTF8_STRING
from .tags import ASN_Tags_MMS


class ASN1_CONFIRMED_REQUEST_PDU(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.CONFIRMED_REQUEST_PDU


class ASN1_INITIATE_REQUEST_PDU(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.INITIATE_REQUEST_PDU


class ASN1_INITIATE_RESPONSE_PDU(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.INITIATE_RESPONSE_PDU


class ASN1_GET_NAME_LIST_REQUEST(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.GET_NAME_LIST_REQUEST


class ASN1_READ_REQUEST(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.READ_REQUEST


class ASN1_WRITE_REQUEST(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.WRITE_REQUEST


class ASN1_VMD_SPECIFIC(ASN1_ISO646_STRING):
    tag = ASN_Tags_MMS.VMD_SPECIFIC


class ASN1_DOMAIN_SPECIFIC(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.DOMAIN_SPECIFIC


class ASN1_AA_SPECIFIC(ASN1_ISO646_STRING):
    tag = ASN_Tags_MMS.AA_SPECIFIC


class ASN1_LOCAL_DETAIL_CALLING(ASN1_INTEGER):
    tag = ASN_Tags_MMS.LOCAL_DETAIL_CALLING


class ASN1_PROPOSED_MAX_SERV_OUTSTANDING_CALLING(ASN1_INTEGER):
    tag = ASN_Tags_MMS.PROPOSED_MAX_SERV_OUTSTANDING_CALLING


class ASN1_PROPOSED_MAX_SERV_OUTSTANDING_CALLED(ASN1_INTEGER):
    tag = ASN_Tags_MMS.PROPOSED_MAX_SERV_OUTSTANDING_CALLED


class ASN1_PROPOSED_DATA_STRUCTURE_NESTING_LEVEL(ASN1_INTEGER):
    tag = ASN_Tags_MMS.PROPOSED_DATA_STRUCTURE_NESTING_LEVEL


class ASN1_MMS_INIT_REQUEST_DETAIL(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.MMS_INIT_REQUEST_DETAIL


class ASN1_PROPOSED_VERSION_NUMBER(ASN1_INTEGER):
    tag = ASN_Tags_MMS.PROPOSED_VERSION_NUMBER


class ASN1_PROPOSED_PARAMETER_CBB(ASN1_BIT_STRING):
    tag = ASN_Tags_MMS.PROPOSED_PARAMETER_CBB


class ASN1_SERVICES_SUPPORTED_CALLING(ASN1_BIT_STRING):
    tag = ASN_Tags_MMS.SERVICES_SUPPORTED_CALLING


class ASN1_LOCAL_DETAIL_CALLED(ASN1_INTEGER):
    tag = ASN_Tags_MMS.LOCAL_DETAIL_CALLED


class ASN1_NEGOTIATED_MAX_SERV_OUTSTANDING_CALLING(ASN1_INTEGER):
    tag = ASN_Tags_MMS.NEGOTIATED_MAX_SERV_OUTSTANDING_CALLING


class ASN1_NEGOTIATED_MAX_SERV_OUTSTANDING_CALLED(ASN1_INTEGER):
    tag = ASN_Tags_MMS.NEGOTIATED_MAX_SERV_OUTSTANDING_CALLED


class ASN1_NEGOTIATED_DATA_STRUCTURE_NESTING_LEVEL(ASN1_INTEGER):
    tag = ASN_Tags_MMS.NEGOTIATED_DATA_STRUCTURE_NESTING_LEVEL


class ASN1_MMS_INIT_RESPONSE_DETAIL(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.MMS_INIT_RESPONSE_DETAIL


class ASN1_NEGOTIATED_VERSION_NUMBER(ASN1_INTEGER):
    tag = ASN_Tags_MMS.NEGOTIATED_VERSION_NUMBER


class ASN1_NEGOTIATED_PARAMETER_CBB(ASN1_BIT_STRING):
    tag = ASN_Tags_MMS.NEGOTIATED_PARAMETER_CBB


class ASN1_SERVICES_SUPPORTED_CALLED(ASN1_BIT_STRING):
    tag = ASN_Tags_MMS.SERVICES_SUPPORTED_CALLED


class ASN1_VMD_STATE(ASN1_INTEGER):
    tag = ASN_Tags_MMS.VMD_STATE


class ASN1_OBJECT_CLASS(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.OBJECT_CLASS


class ASN1_OBJECT_SCOPE(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.OBJECT_SCOPE


class ASN1_OBJECT_SCOPE_VMD_SPECIFIC(ASN1_NULL):
    tag = ASN_Tags_MMS.OBJECT_SCOPE_VMD_SPECIFIC


class ASN1_OBJECT_SCOPE_DOMAIN_SPECIFIC(ASN1_ISO646_STRING):
    tag = ASN_Tags_MMS.OBJECT_SCOPE_DOMAIN_SPECIFIC


class ASN1_OBJECT_SCOPE_AA_SPECIFIC(ASN1_NULL):
    tag = ASN_Tags_MMS.OBJECT_SCOPE_AA_SPECIFIC


class ASN1_BASIC_OBJECT_CLASS(ASN1_INTEGER):
    tag = ASN_Tags_MMS.BASIC_OBJECT_CLASS


class ASN1_TYPE_SPECIFICATION_MMS_STRING(ASN1_INTEGER):
    tag = ASN_Tags_MMS.TYPE_SPECIFICATION_MMS_STRING


class ASN1_READ_REQUEST_SPECIFICATION_WITH_RESULT(ASN1_BOOLEAN):
    tag = ASN_Tags_MMS.READ_REQUEST_SPECIFICATION_WITH_RESULT


class ASN1_READ_REQUEST_VARIABLE_ACCESS_SPECIFICATION(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.READ_REQUEST_VARIABLE_ACCESS_SPECIFICATION


class ASN1_LIST_OF_DATA(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.LIST_OF_DATA


class ASN1_NAME(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.NAME


class ASN1_DATA_TYPE_BOOLEAN_(ASN1_BOOLEAN):
    tag = ASN_Tags_MMS.DATA_TYPE_BOOLEAN_


class ASN1_DATA_TYPE_BIT_STRING(ASN1_BIT_STRING):
    tag = ASN_Tags_MMS.DATA_TYPE_BIT_STRING


class ASN1_DATA_TYPE_INTEGER(ASN1_INTEGER):
    tag = ASN_Tags_MMS.DATA_TYPE_INTEGER


class ASN1_DATA_TYPE_UNSIGNED(ASN1_INTEGER):
    tag = ASN_Tags_MMS.DATA_TYPE_UNSIGNED


class ASN1_DATA_TYPE_FLOATING_POINT(ASN1_STRING):
    tag = ASN_Tags_MMS.DATA_TYPE_FLOATING_POINT


class ASN1_DATA_TYPE_OCTET_STRING(ASN1_STRING):
    tag = ASN_Tags_MMS.DATA_TYPE_OCTET_STRING


class ASN1_DATA_TYPE_VISIBLE_STRING(ASN1_ISO646_STRING):
    tag = ASN_Tags_MMS.DATA_TYPE_VISIBLE_STRING


class ASN1_DATA_TYPE_BINARY_TIME(ASN1_STRING):
    tag = ASN_Tags_MMS.DATA_TYPE_BINARY_TIME


class ASN1_DATA_TYPE_MMS_STRING(ASN1_UTF8_STRING):
    tag = ASN_Tags_MMS.DATA_TYPE_MMS_STRING


class ASN1_DATA_TYPE_UTC_TIME(ASN1_STRING):
    tag = ASN_Tags_MMS.DATA_TYPE_UTC_TIME


class ASN1_LIST_OF_VARIABLES(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.VARIABLE_ACCESS_SPECIFICATION_LIST_OF_VARIABLE


class ASN1_VARIABLES_LIST_NAMES(ASN1_SEQUENCE):
    tag = ASN_Tags_MMS.VARIABLE_ACCESS_SPECIFICATION_VARIABLE_LIST_NAME
